# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='add_tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='Тэги'),
        ),
    ]
