# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160902_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='Тег'),
        ),
    ]
