# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-13 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160908_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='add_tags',
            field=models.ManyToManyField(default=None, to='blog.Tag', verbose_name='Тэги'),
        ),
    ]
