# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-14 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='add_comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comments', verbose_name='Комментарии'),
        ),
    ]
