# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_add_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='add_comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(max_length=30, verbose_name='Автор'),
        ),
    ]
